# File: doc-ms/docker-compose.yml
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: doc-ms
    # labels:
    #   - traefik.enable=true
    networks:
      - traefik
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    networks:          
      - traefik
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

# networks:
#   traefik:
#     external: true


networks:
  traefik:
    name: traefik # Ensure this matches the network used by Traefik

volumes:
  postgres_data:
